/*copie mel 234 hta 299
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Memo;

import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author user
 */
public class author extends javax.swing.JFrame {

    /**
     * Creates new form author
     */
Connection conn=null;
ResultSet rs=null;
PreparedStatement stmt=null;
    /**
     * Creates new form finder
     */
    public author() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        lb1.setVisible(false);
        lb2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("jdbc:sqlite:C:\\Users\\user\\Desktop\\la mémoire\\memo\\auteur.dbPU").createEntityManager();
        documentQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM Document d");
        documentList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : documentQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_img = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_bio = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        auteur_search = new javax.swing.JButton();
        txt_auteur = new javax.swing.JTextField();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_doc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(null);

        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Memo/Image/poem.png"))); // NOI18N
        jPanel2.add(lbl_img);
        lbl_img.setBounds(150, 70, 128, 142);
        jPanel2.add(txt_id);
        txt_id.setBounds(110, 250, 201, 28);
        jPanel2.add(txt_nom);
        txt_nom.setBounds(110, 290, 201, 28);
        jPanel2.add(txt_prenom);
        txt_prenom.setBounds(110, 330, 201, 28);

        txt_bio.setColumns(20);
        txt_bio.setRows(5);
        jScrollPane1.setViewportView(txt_bio);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(110, 370, 201, 100);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 250, 56, 28);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Family name:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 290, 100, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 330, 70, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bio:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 380, 50, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 380, 518);

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(1000, 0, 54, 50);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText(" Search by document author");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 10, 451, 53);

        auteur_search.setBackground(new java.awt.Color(0, 102, 204));
        auteur_search.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        auteur_search.setForeground(new java.awt.Color(255, 255, 255));
        auteur_search.setText("Search");
        auteur_search.setBorder(null);
        auteur_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        auteur_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auteur_searchActionPerformed(evt);
            }
        });
        jPanel1.add(auteur_search);
        auteur_search.setBounds(930, 60, 120, 40);

        txt_auteur.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt_auteur.setForeground(new java.awt.Color(51, 51, 51));
        txt_auteur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel1.add(txt_auteur);
        txt_auteur.setBounds(405, 60, 520, 37);

        lb1.setText("jLabel2");
        jPanel1.add(lb1);
        lb1.setBounds(420, 490, 34, 14);

        lb2.setText("jLabel2");
        jPanel1.add(lb2);
        lb2.setBounds(730, 493, 171, 14);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, documentList, table_doc);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${author}"));
        columnBinding.setColumnName("Author");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${namedocument}"));
        columnBinding.setColumnName("Namedocument");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pathdocument}"));
        columnBinding.setColumnName("Pathdocument");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        table_doc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_docMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_doc);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(400, 110, 650, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1054, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // if you click on the X
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void auteur_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auteur_searchActionPerformed
        // search by author of the document
        
        String auteur_nom=txt_auteur.getText();
              
        conn=database.java_db();
        try {
            //le travaill de auteur
            if(auteur_nom.isEmpty()){
                JOptionPane.showMessageDialog(null, "please insert a value");
            } else {
            }
        String sql="SELECT * FROM document WHERE Author LIKE '%"+auteur_nom+"%'";
         stmt=conn.prepareStatement(sql);
         rs=stmt.executeQuery();
         table_doc.setModel(DbUtils.resultSetToTableModel(rs));
         
        //la cart de auteur 
         String sql2 ="select * from auteur where Family_name_author=? ";
           
            stmt=conn.prepareStatement(sql2);
            stmt.setString(1,txt_auteur.getText());
            rs=stmt.executeQuery();            
            
            String chemp=rs.getString("Image");
            lb1.setText(chemp);
            lb1.setVisible(false);            
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(chemp).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH));
            //lbl_img.setIcon(imageIcon);
            
            String add1 =rs.getString("ID");
            txt_id.setText(add1);
            
            String add2 =rs.getString("Family_name_author");
            txt_nom.setText(add2);
            
            String add3 =rs.getString("Name_author");
            txt_prenom.setText(add3);
            
            String add4 =rs.getString("Bio_author");
            txt_bio.setText(add4);             
            
        } catch(Exception e)

        {
             //JOptionPane.showMessageDialog(null, e);
             JOptionPane.showMessageDialog(null, "this author does not exist");

        }
        finally {
            
            try{
                rs.close();
                stmt.close();
                
            }
            catch(Exception e){
                
            }
        
        }
    }

    private void table_docMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_docMouseClicked
        // if you want to open the document
            int index = table_doc.getSelectedRow();
            TableModel model = table_doc.getModel();
            lb1.setText(model.getValueAt(index, 3).toString());//mettre le chemp dans path_doc HROZ MEL NIMIRO TA3 COLOMN
            
            File filepath=new File(lb1.getText());
    try {
        Desktop.getDesktop().open(filepath);
    } catch (Exception e) {
                     JOptionPane.showMessageDialog(null, e);

    }
    }//GEN-LAST:event_table_docMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(author.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new author().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton auteur_search;
    private java.util.List<Memo.Document> documentList;
    private javax.persistence.Query documentQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTable table_doc;
    private javax.swing.JTextField txt_auteur;
    private javax.swing.JTextArea txt_bio;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
